import type { Metadata } from "next"
import "./globals.css"
import { Preahvihear } from "next/font/google"

const preahvihear = Preahvihear({
  weight: ["400"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Eder | Portfólio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={preahvihear.className}>
        {children}
      </body>
    </html>
  );
}
