import type { Metadata } from "next"
import "./globals.css"
import { Preahvihear } from "next/font/google"
import { I18nProvider } from "@/contexts/I18nProvider"

const preahvihear = Preahvihear({
  weight: ["400"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Eder | Portfólio",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={preahvihear.className}>
        <I18nProvider>
          {children}
        </I18nProvider>
      </body>
    </html>
  )
}
