import type { Metadata } from "next"
import "./globals.css"
import { Preahvihear } from "next/font/google"
import { LanguageProvider } from "@/contexts/LanguageContext"
import { headers } from "next/headers"

const preahvihear = Preahvihear({
  weight: ["400"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Eder | Portfólio",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const headersList = await headers()
  const acceptLanguage = headersList.get("accept-language")
  const defaultLocale = acceptLanguage?.includes("pt") ? "pt" : "en"

  return (
    <html lang={defaultLocale}>
      <body className={preahvihear.className}>
        <LanguageProvider>
          {children}
        </LanguageProvider>
      </body>
    </html>
  )
}
